'use client'

import { useEffect, useState, useRef } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { 
  ArrowLeft, 
  ExternalLink, 
  AlertTriangle, 
  AlertCircle, 
  Info,
  CheckCircle2,
  Loader2,
  ArrowRight,
  Eye,
  Lightbulb,
  Download,
  FileJson,
  FileText,
  Printer
} from 'lucide-react'
import { formatDate, getScoreColor, getScoreBgColor, cn } from '@/lib/utils'

interface UXIssue {
  id: string
  category: 'clarity' | 'layout' | 'navigation' | 'accessibility' | 'trust'
  severity: 'high' | 'medium' | 'low'
  title: string
  description: string
  proof: string
  element?: string
}

interface BeforeAfterSuggestion {
  issueId: string
  title: string
  before: string
  after: string
  explanation: string
}

interface Review {
  id: string
  url: string
  title: string
  screenshot: string
  issues: UXIssue[]
  suggestions: BeforeAfterSuggestion[]
  score: number
  createdAt: string
}

const categoryColors = {
  clarity: 'bg-blue-100 text-blue-700 border-blue-200',
  layout: 'bg-purple-100 text-purple-700 border-purple-200',
  navigation: 'bg-green-100 text-green-700 border-green-200',
  accessibility: 'bg-orange-100 text-orange-700 border-orange-200',
  trust: 'bg-pink-100 text-pink-700 border-pink-200',
}

const severityIcons = {
  high: AlertTriangle,
  medium: AlertCircle,
  low: Info,
}

const severityColors = {
  high: 'text-red-500',
  medium: 'text-yellow-500',
  low: 'text-blue-500',
}

export default function ReviewPage() {
  const params = useParams()
  const [review, setReview] = useState<Review | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [activeTab, setActiveTab] = useState<'issues' | 'suggestions'>('issues')
  const [showExportMenu, setShowExportMenu] = useState(false)
  const exportMenuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    async function fetchReview() {
      try {
        const response = await fetch(`/api/reviews/${params.id}`)
        if (!response.ok) {
          throw new Error('Review not found')
        }
        const data = await response.json()
        setReview(data)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load review')
      } finally {
        setLoading(false)
      }
    }

    if (params.id) {
      fetchReview()
    }
  }, [params.id])

  // Close export menu when clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (exportMenuRef.current && !exportMenuRef.current.contains(event.target as Node)) {
        setShowExportMenu(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  // Export as JSON
  const exportAsJSON = () => {
    if (!review) return
    const dataStr = JSON.stringify(review, null, 2)
    const blob = new Blob([dataStr], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `ux-review-${review.id}.json`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    setShowExportMenu(false)
  }

  // Export as Text/Markdown
  const exportAsText = () => {
    if (!review) return
    
    let text = `# UX Review Report\n\n`
    text += `**Website:** ${review.title}\n`
    text += `**URL:** ${review.url}\n`
    text += `**Date:** ${formatDate(review.createdAt)}\n`
    text += `**UX Score:** ${review.score}/100\n\n`
    text += `---\n\n`
    text += `## Issues Found (${review.issues.length})\n\n`
    
    const issuesByCategory = review.issues.reduce((acc, issue) => {
      if (!acc[issue.category]) acc[issue.category] = []
      acc[issue.category].push(issue)
      return acc
    }, {} as Record<string, UXIssue[]>)
    
    Object.entries(issuesByCategory).forEach(([category, issues]) => {
      text += `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n`
      issues.forEach((issue, i) => {
        text += `**${i + 1}. ${issue.title}** [${issue.severity.toUpperCase()}]\n`
        text += `${issue.description}\n`
        text += `> Evidence: ${issue.proof}\n\n`
      })
    })
    
    if (review.suggestions.length > 0) {
      text += `---\n\n## Recommendations\n\n`
      review.suggestions.forEach((suggestion, i) => {
        text += `### ${i + 1}. ${suggestion.title}\n\n`
        text += `**Before:** ${suggestion.before}\n\n`
        text += `**After:** ${suggestion.after}\n\n`
        text += `*${suggestion.explanation}*\n\n`
      })
    }
    
    text += `---\n\n*Generated by UX Reviewer*\n`
    
    const blob = new Blob([text], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `ux-review-${review.id}.md`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    setShowExportMenu(false)
  }

  // Print / Save as PDF
  const exportAsPDF = () => {
    setShowExportMenu(false)
    window.print()
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
      </div>
    )
  }

  if (error || !review) {
    return (
      <div className="max-w-2xl mx-auto text-center py-12">
        <AlertCircle className="w-16 h-16 text-red-500 mx-auto mb-4" />
        <h1 className="text-2xl font-bold text-slate-800 mb-2">Review Not Found</h1>
        <p className="text-slate-600 mb-6">{error || 'The review you are looking for does not exist.'}</p>
        <Link href="/" className="btn-primary">
          <ArrowLeft className="w-4 h-4 mr-2 inline" />
          Back to Home
        </Link>
      </div>
    )
  }

  const issuesByCategory = review.issues.reduce((acc, issue) => {
    if (!acc[issue.category]) {
      acc[issue.category] = []
    }
    acc[issue.category].push(issue)
    return acc
  }, {} as Record<string, UXIssue[]>)

  const highSeverityCount = review.issues.filter(i => i.severity === 'high').length
  const mediumSeverityCount = review.issues.filter(i => i.severity === 'medium').length
  const lowSeverityCount = review.issues.filter(i => i.severity === 'low').length

  return (
    <div className="max-w-5xl mx-auto print:max-w-none">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4 print:hidden">
          <Link href="/" className="inline-flex items-center text-slate-600 hover:text-slate-800">
            <ArrowLeft className="w-4 h-4 mr-1" />
            Back to Home
          </Link>
          
          {/* Export Button */}
          <div className="relative" ref={exportMenuRef}>
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="btn-secondary flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Export Report
            </button>
            
            {showExportMenu && (
              <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-slate-200 py-2 z-50">
                <button
                  onClick={exportAsPDF}
                  className="w-full px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                >
                  <Printer className="w-4 h-4" />
                  Print / Save as PDF
                </button>
                <button
                  onClick={exportAsText}
                  className="w-full px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                >
                  <FileText className="w-4 h-4" />
                  Export as Markdown
                </button>
                <button
                  onClick={exportAsJSON}
                  className="w-full px-4 py-2 text-left text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                >
                  <FileJson className="w-4 h-4" />
                  Export as JSON
                </button>
              </div>
            )}
          </div>
        </div>
        
        {/* Print Header - Only visible when printing */}
        <div className="hidden print:block mb-6">
          <h1 className="text-3xl font-bold text-slate-800">UX Review Report</h1>
          <p className="text-slate-600">Generated by UX Reviewer</p>
        </div>
        
        <div className="card print:shadow-none print:border-2">
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
            <div className="flex-1">
              <h1 className="text-2xl font-bold text-slate-800 mb-2 print:text-xl">{review.title}</h1>
              <a 
                href={review.url} 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center text-primary-600 hover:text-primary-700 print:text-slate-600"
              >
                {review.url}
                <ExternalLink className="w-4 h-4 ml-1 print:hidden" />
              </a>
              <p className="text-sm text-slate-500 mt-2">
                Analyzed {formatDate(review.createdAt)}
              </p>
            </div>
            
            <div className={cn('text-center p-4 rounded-xl print:border-2', getScoreBgColor(review.score))}>
              <div className={cn('text-4xl font-bold print:text-3xl', getScoreColor(review.score))}>
                {review.score}
              </div>
              <div className="text-sm text-slate-600">UX Score</div>
            </div>
          </div>

          {/* Summary Stats */}
          <div className="grid grid-cols-3 gap-4 mt-6 pt-6 border-t border-slate-200">
            <div className="text-center">
              <div className="flex items-center justify-center gap-1 text-red-500">
                <AlertTriangle className="w-4 h-4" />
                <span className="text-2xl font-bold">{highSeverityCount}</span>
              </div>
              <div className="text-sm text-slate-600">High Priority</div>
            </div>
            <div className="text-center">
              <div className="flex items-center justify-center gap-1 text-yellow-500">
                <AlertCircle className="w-4 h-4" />
                <span className="text-2xl font-bold">{mediumSeverityCount}</span>
              </div>
              <div className="text-sm text-slate-600">Medium Priority</div>
            </div>
            <div className="text-center">
              <div className="flex items-center justify-center gap-1 text-blue-500">
                <Info className="w-4 h-4" />
                <span className="text-2xl font-bold">{lowSeverityCount}</span>
              </div>
              <div className="text-sm text-slate-600">Low Priority</div>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs - Hidden in print */}
      <div className="flex gap-2 mb-6 print:hidden">
        <button
          onClick={() => setActiveTab('issues')}
          className={cn(
            'flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors',
            activeTab === 'issues'
              ? 'bg-primary-100 text-primary-700'
              : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
          )}
        >
          <Eye className="w-4 h-4" />
          Issues ({review.issues.length})
        </button>
        <button
          onClick={() => setActiveTab('suggestions')}
          className={cn(
            'flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors',
            activeTab === 'suggestions'
              ? 'bg-primary-100 text-primary-700'
              : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
          )}
        >
          <Lightbulb className="w-4 h-4" />
          Before/After ({review.suggestions.length})
        </button>
      </div>

      {/* Issues Section - Show in print, or when tab is active */}
      <div className={cn(activeTab !== 'issues' && 'hidden print:block')}>
        <h2 className="hidden print:block text-xl font-bold text-slate-800 mb-4">Issues Found</h2>
        <div className="space-y-6">
          {Object.entries(issuesByCategory).map(([category, issues]) => (
            <div key={category} className="card print:shadow-none print:border print:break-inside-avoid">
              <h2 className="text-lg font-semibold text-slate-800 mb-4 capitalize flex items-center gap-2">
                <span className={cn('px-2 py-1 rounded text-sm', categoryColors[category as keyof typeof categoryColors])}>
                  {category}
                </span>
                <span className="text-slate-400 text-sm font-normal">
                  {issues.length} issue{issues.length !== 1 ? 's' : ''}
                </span>
              </h2>
              
              <div className="space-y-4">
                {issues.map((issue) => {
                  const SeverityIcon = severityIcons[issue.severity]
                  return (
                    <div 
                      key={issue.id} 
                      className="border border-slate-200 rounded-lg p-4 hover:border-slate-300 transition-colors print:break-inside-avoid"
                    >
                      <div className="flex items-start gap-3">
                        <SeverityIcon className={cn('w-5 h-5 mt-0.5 flex-shrink-0', severityColors[issue.severity])} />
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <h3 className="font-medium text-slate-800">{issue.title}</h3>
                            <span className={cn(
                              'text-xs px-2 py-0.5 rounded-full',
                              issue.severity === 'high' ? 'bg-red-100 text-red-700' :
                              issue.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                              'bg-blue-100 text-blue-700'
                            )}>
                              {issue.severity}
                            </span>
                          </div>
                          <p className="text-slate-600 text-sm mb-3">{issue.description}</p>
                          <div className="bg-slate-50 rounded-lg p-3">
                            <div className="text-xs text-slate-500 uppercase tracking-wide mb-1">Evidence</div>
                            <p className="text-sm text-slate-700 font-mono">{issue.proof}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Suggestions Section - Show in print, or when tab is active */}
      <div className={cn(activeTab !== 'suggestions' && 'hidden print:block', 'print:mt-8')}>
        <h2 className="hidden print:block text-xl font-bold text-slate-800 mb-4">Recommendations</h2>
        <div className="space-y-6">
          {review.suggestions.length === 0 ? (
            <div className="card text-center py-8 print:hidden">
              <Lightbulb className="w-12 h-12 text-slate-300 mx-auto mb-4" />
              <p className="text-slate-600">No before/after suggestions available.</p>
            </div>
          ) : (
            review.suggestions.map((suggestion, index) => (
              <div key={suggestion.issueId} className="card print:shadow-none print:border print:break-inside-avoid">
                <div className="flex items-center gap-2 mb-4">
                  <span className="w-8 h-8 rounded-full bg-primary-100 text-primary-700 font-bold flex items-center justify-center">
                    {index + 1}
                  </span>
                  <h3 className="text-lg font-semibold text-slate-800">{suggestion.title}</h3>
                </div>
                
                <div className="grid md:grid-cols-2 gap-4 mb-4">
                  <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                    <div className="text-xs text-red-600 uppercase tracking-wide mb-2 font-medium">Before</div>
                    <p className="text-slate-700">{suggestion.before}</p>
                  </div>
                  <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                    <div className="text-xs text-green-600 uppercase tracking-wide mb-2 font-medium">After</div>
                    <p className="text-slate-700">{suggestion.after}</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-2 text-slate-600 bg-slate-50 rounded-lg p-3">
                  <CheckCircle2 className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                  <p className="text-sm">{suggestion.explanation}</p>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Action Buttons - Hidden in print */}
      <div className="mt-8 flex justify-center gap-4 print:hidden">
        <Link href="/" className="btn-secondary">
          Analyze Another Site
        </Link>
        <Link href="/history" className="btn-primary">
          View All Reviews
          <ArrowRight className="w-4 h-4 ml-2 inline" />
        </Link>
      </div>
      
      {/* Print Footer */}
      <div className="hidden print:block mt-8 pt-4 border-t border-slate-200 text-center text-sm text-slate-500">
        Generated by UX Reviewer | {new Date().toLocaleDateString()}
      </div>
    </div>
  )
}
